- name: Set fast mirror
  become: yes
  replace:
    path: /etc/apt/sources.list
    regexp: 'http:\/\/.*\.ubuntu\.com'
    replace: 'http://mirror.waia.asn.au'
    backup: yes

- name: Upgrade packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
    autoclean: yes
    purge: yes
  